# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 336)
        MainWindow.setStyleSheet("QPushButton {\n"
"  font-size: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"  font-size: 20px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doo = QtWidgets.QPushButton(self.centralwidget)
        self.doo.setMinimumSize(QtCore.QSize(90, 90))
        self.doo.setMaximumSize(QtCore.QSize(90, 90))
        self.doo.setObjectName("doo")
        self.buttons = QtWidgets.QButtonGroup(MainWindow)
        self.buttons.setObjectName("buttons")
        self.buttons.addButton(self.doo)
        self.horizontalLayout.addWidget(self.doo)
        self.re = QtWidgets.QPushButton(self.centralwidget)
        self.re.setMinimumSize(QtCore.QSize(90, 90))
        self.re.setMaximumSize(QtCore.QSize(90, 90))
        self.re.setObjectName("re")
        self.buttons.addButton(self.re)
        self.horizontalLayout.addWidget(self.re)
        self.mi = QtWidgets.QPushButton(self.centralwidget)
        self.mi.setMinimumSize(QtCore.QSize(90, 90))
        self.mi.setMaximumSize(QtCore.QSize(90, 90))
        self.mi.setObjectName("mi")
        self.buttons.addButton(self.mi)
        self.horizontalLayout.addWidget(self.mi)
        self.fa = QtWidgets.QPushButton(self.centralwidget)
        self.fa.setMinimumSize(QtCore.QSize(90, 90))
        self.fa.setMaximumSize(QtCore.QSize(90, 90))
        self.fa.setObjectName("fa")
        self.buttons.addButton(self.fa)
        self.horizontalLayout.addWidget(self.fa)
        self.sol = QtWidgets.QPushButton(self.centralwidget)
        self.sol.setMinimumSize(QtCore.QSize(90, 90))
        self.sol.setMaximumSize(QtCore.QSize(90, 90))
        self.sol.setObjectName("sol")
        self.buttons.addButton(self.sol)
        self.horizontalLayout.addWidget(self.sol)
        self.lya = QtWidgets.QPushButton(self.centralwidget)
        self.lya.setMinimumSize(QtCore.QSize(90, 90))
        self.lya.setMaximumSize(QtCore.QSize(90, 90))
        self.lya.setObjectName("lya")
        self.buttons.addButton(self.lya)
        self.horizontalLayout.addWidget(self.lya)
        self.si = QtWidgets.QPushButton(self.centralwidget)
        self.si.setMinimumSize(QtCore.QSize(90, 90))
        self.si.setMaximumSize(QtCore.QSize(90, 90))
        self.si.setObjectName("si")
        self.buttons.addButton(self.si)
        self.horizontalLayout.addWidget(self.si)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "На клавиатуре 1 2 3 4 5 6 7"))
        self.doo.setText(_translate("MainWindow", "до"))
        self.re.setText(_translate("MainWindow", "ре"))
        self.mi.setText(_translate("MainWindow", "ми"))
        self.fa.setText(_translate("MainWindow", "фа"))
        self.sol.setText(_translate("MainWindow", "соль"))
        self.lya.setText(_translate("MainWindow", "ля"))
        self.si.setText(_translate("MainWindow", "си"))
